apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::855655753923:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::855655753923:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IE3F0A5RIIST
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-26T20:42:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1388"
  uid: 63b8ee03-c841-440e-bfb0-f0d0a6e93ddc
